%facts
task(psychomotorvigilance)
button(acknowledge)
subject(subject)
container(container)
target(target)
isPartOf(subject,psychomotorvigilance)
isPartOf(acknowledge,psychomotorvigilance)
isPartOf(container,psychomotorvigilance)
isPartOf(target,psychomotorvigilance)

%rules
target(L)->letter(L)
isPartOf(C,A)^task(A)^subject(C)->hasProperty(A,active)
target(J)^subject(C)^appearsIn(J,H)^container(H)^button(E)->remember(C,J)
target(J)^subject(C)^appearsIn(J,H)^container(H)^button(E)->click(C,E)
task(A)^hasProperty(A,active)^target(J)^container(H)->appearsIn(J,H)
