%facts
task(psychomotorvigilance).
button(acknowledge).
subject(subject).
_box(_box).
target(target).
isPartOf(subject,psychomotorvigilance).
isPartOf(acknowledge,psychomotorvigilance).
isPartOf(_box,psychomotorvigilance).
isPartOf(target,psychomotorvigilance).

%rules
letter(L) :- target(L).
hasProperty(A,active) :- subject(C),task(A),isPartOf(C,A).
click(C,E) :- subject(C),appearsIn(J,H),_box(H),button(E),target(J).
remember(C,J) :- subject(C),appearsIn(J,H),_box(H),button(E),target(J).
appearsIn(J,H) :- task(A),hasProperty(A,active),target(J),_box(H).

%queries
letter(L)?
hasProperty(A,active)?
click(C,E)?
remember(C,J)?
appearsIn(J,H)?
