%facts
task(psychomotorvigilance)
button(acknowledge)
subject(subject)
container(container)
target(target)
isPartOf(subject,psychomotorvigilance)
isPartOf(acknowledge,psychomotorvigilance)
isPartOf(container,psychomotorvigilance)
isPartOf(target,psychomotorvigilance)

%rules
target(L)->letter(L)
subject(C)^isPartOf(C,A)^task(A)->hasProperty(A,active)
container(H)^button(E)^subject(C)^appearsIn(J,H)^target(J)->remember(C,J)
container(H)^button(E)^subject(C)^appearsIn(J,H)^target(J)->click(C,E)
task(A)^hasProperty(A,active)^target(J)^container(H)->appearsIn(J,H)
